# fly.toml app configuration file for legal-laravel-crm
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "legal-laravel-crm" # TODO: Change to your app name
primary_region = "ams"    # TODO: Change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  APP_NAME = "Legal CRM"
  APP_ENV = "production"
  APP_DEBUG = false
  APP_URL = "https://legal-laravel-crm.fly.dev" # TODO: Change to your actual URL
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  DB_CONNECTION = "pgsql"
  # TODO: Update with your database connection details from `flyctl pg attach` or your dashboard
  # DB_HOST = "top2.nearest.of.your-db-app.internal"
  # DB_PORT = 5432
  # DB_DATABASE = "your_db_name"

  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  FILESYSTEM_DISK = "local"
  QUEUE_CONNECTION = "database" # Use "redis" if you set up a Redis instance
  SESSION_DRIVER = "file"       # Use "redis" or "cookie" for multi-node setups
  SESSION_LIFETIME = "120"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Set to 1 for an always-on application
  processes = ["app"]

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/"

[deploy]
  release_command = "php artisan migrate --force"

# This defines the VM size for your web server process
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 # Adjust as needed
  processes = ["app"]